###
POST https://valheim.help/api/TrackTrophies
Content-Type: application/json

{
  "test": "test"
}

###
GET https://valheim.help/api/TrackTrophies
Content-Type: application/json


###
POST http://localhost:4321/api/TrackTrophies
Content-Type: application/json

{
  "test": "test"
}

###
GET http://localhost:4321/api/TrackTrophies
Content-Type: application/json
