###
POST https://valheim.help/api/trackhunt
Content-Type: application/json

{
    "current_score": 50,
    "deaths": 2,
    "logouts": 0,
    "player_location": "(5.73, 35.53, 3.60)",
    "player_name": "oathorse",
    "session_id": "372745983",
    "trophies": "TrophyDeer, TrophyBoar"
}





###
POST http://localhost:7071/api/trackhunt
Content-Type: application/json

{
    "current_score": 50,
    "deaths": 2,
    "logouts": 0,
    "player_location": "(5.73, 35.53, 3.60)",
    "player_name": "jarrettv",
    "session_id": "372745983",
    "trophies": "TrophyGreydwarf, TrophyDeer, TrophyBoar, TrophyNeck, TrophyEikthyr"
}
