/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TrophyCalcImport } from './routes/trophy-calc'
import { Route as GearInfoImport } from './routes/gear-info'
import { Route as FoodInfoImport } from './routes/food-info'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TrophyCalcRoute = TrophyCalcImport.update({
  path: '/trophy-calc',
  getParentRoute: () => rootRoute,
} as any)

const GearInfoRoute = GearInfoImport.update({
  path: '/gear-info',
  getParentRoute: () => rootRoute,
} as any)

const FoodInfoRoute = FoodInfoImport.update({
  path: '/food-info',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/food-info': {
      id: '/food-info'
      path: '/food-info'
      fullPath: '/food-info'
      preLoaderRoute: typeof FoodInfoImport
      parentRoute: typeof rootRoute
    }
    '/gear-info': {
      id: '/gear-info'
      path: '/gear-info'
      fullPath: '/gear-info'
      preLoaderRoute: typeof GearInfoImport
      parentRoute: typeof rootRoute
    }
    '/trophy-calc': {
      id: '/trophy-calc'
      path: '/trophy-calc'
      fullPath: '/trophy-calc'
      preLoaderRoute: typeof TrophyCalcImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  FoodInfoRoute,
  GearInfoRoute,
  TrophyCalcRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/food-info",
        "/gear-info",
        "/trophy-calc"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/food-info": {
      "filePath": "food-info.tsx"
    },
    "/gear-info": {
      "filePath": "gear-info.tsx"
    },
    "/trophy-calc": {
      "filePath": "trophy-calc.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
