/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TrophyCalcImport } from './routes/trophy-calc'
import { Route as IndexImport } from './routes/index'
import { Route as GearIndexImport } from './routes/gear.index'
import { Route as FoodIndexImport } from './routes/food.index'
import { Route as GearGearIdImport } from './routes/gear.$gearId'

// Create/Update Routes

const TrophyCalcRoute = TrophyCalcImport.update({
  path: '/trophy-calc',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const GearIndexRoute = GearIndexImport.update({
  path: '/gear/',
  getParentRoute: () => rootRoute,
} as any)

const FoodIndexRoute = FoodIndexImport.update({
  path: '/food/',
  getParentRoute: () => rootRoute,
} as any)

const GearGearIdRoute = GearGearIdImport.update({
  path: '/gear/$gearId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/trophy-calc': {
      id: '/trophy-calc'
      path: '/trophy-calc'
      fullPath: '/trophy-calc'
      preLoaderRoute: typeof TrophyCalcImport
      parentRoute: typeof rootRoute
    }
    '/gear/$gearId': {
      id: '/gear/$gearId'
      path: '/gear/$gearId'
      fullPath: '/gear/$gearId'
      preLoaderRoute: typeof GearGearIdImport
      parentRoute: typeof rootRoute
    }
    '/food/': {
      id: '/food/'
      path: '/food'
      fullPath: '/food'
      preLoaderRoute: typeof FoodIndexImport
      parentRoute: typeof rootRoute
    }
    '/gear/': {
      id: '/gear/'
      path: '/gear'
      fullPath: '/gear'
      preLoaderRoute: typeof GearIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  TrophyCalcRoute,
  GearGearIdRoute,
  FoodIndexRoute,
  GearIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/trophy-calc",
        "/gear/$gearId",
        "/food/",
        "/gear/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/trophy-calc": {
      "filePath": "trophy-calc.tsx"
    },
    "/gear/$gearId": {
      "filePath": "gear.$gearId.tsx"
    },
    "/food/": {
      "filePath": "food.index.tsx"
    },
    "/gear/": {
      "filePath": "gear.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
